[package]
name = "c_interop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bmp = "0.5.0"
glob = "0.3.1"
num-traits = "0.2.16"
pad = "0.1.6"

[build-dependencies]
glob = "0.3.1"
cc = "1.0"
